### ISSUE TITLE
Mongo time out error

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#1]
someone must handle mongodb errors related to timeout when preforming a query or when establishing the connection

`
 message: 'failed to connect to server [timed out exception]'
`
@amja-do

**Comment by muttaqin1** [comment]
If i am right you are facing errors when the server failed to connect to the database.You want to catch that error and handle right?

**Comment by muttaqin1** [comment]
I have  resolved the issue.check my pull request.

**Comment by bellaabdelouahab** [comment]
thank you for the quick response
