### ISSUE TITLE
Fix - app error

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#103]
throw the project you might find many approaches :

```js
new AppError(404, 'fail', 'No document found with that id')
```
```js
new AppError('You are not allowed to update this calendar', 403)
```
i think that the second one is better since you might find many other status other than fail and success and also the status code is descriptive

tasks
- [x] change the class definition to include only statusCode and message and path(optional)
- [x] remove or update the accruing of the previous approach from the api

**Comment by bellaabdelouahab** [comment]
can you take this one ?
@muttaqin1

**Comment by muttaqin1** [comment]
> can you take this one ?
> @muttaqin1 

Sure

**Comment by bellaabdelouahab** [comment]
I fixed this
@muttaqin1
