### ISSUE TITLE
Enhancement - Consider Switching to ES6 Import Syntax 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#106]
Hey everyone,

I've been exploring the benefits of using ES6 import syntax over require in our project:

- 🌱 Smoother static analysis for cleaner code.
- 🚀 Selective named imports for efficiency.
- ⚡️ Top-level await for async simplicity.
- ♻️ Consistency with modern JavaScript trends.

Let's discuss if this switch could enhance our project's maintainability and performance.

**Comment by bellaabdelouahab** [comment]
@muttaqin1 
this will require adding .js in every import are you okay with that

**Comment by muttaqin1** [comment]
> @muttaqin1 
> this will require adding .js in every import are you okay with that

Yes
