### ISSUE TITLE
GitHub Workflow : the node.yaml action is not valid 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#114]
because we have two projects inside one backend and frontend i found an issue running the nodejs workflow on the back end,

does any one have an idea about how to fix it ?

**Comment by Mustapha-AitAbd** [comment]
@bellaabdelouahab are both projects running in the same port?

**Comment by bellaabdelouahab** [comment]
The problem is that the workflow tries to find tge package.json but it fails because it's is not on the base dir,
It is inside a sub folder

**Comment by bellaabdelouahab** [comment]
any updates 
@Mustapha-AitAbd

**Comment by Mustapha-AitAbd** [comment]
Not yet, I tried to find a solution
