### ISSUE TITLE
Fix code scanning alert - Server-side URL redirect

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#115]
Tracking issue for:
- [ ] https://github.com/ISIL-ESTE/Student-Workflow-Organizer/security/code-scanning/150

**Comment by muttaqin1** [comment]
I'm unable to access this url.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Oh, my bad.
it is a security alert :
in  [  backend-app/controllers/auth_controllers/auth_controller.js:64  ]
it shows that : Untrusted URL redirection depends on a user provided value

@muttaqin1 

bot description
`
Directly incorporating user input into a URL redirect request without validating the input can facilitate phishing attacks. In these attacks, unsuspecting users can be redirected to a malicious site that looks very similar to the real site they intend to visit, but which is controlled by the attacker.
`

**Comment by muttaqin1** [comment]
> Oh, my bad.
> it is a security alert :
> in  [  backend-app/controllers/auth_controllers/auth_controller.js:64  ]
> it shows that : Untrusted URL redirection depends on a user provided value
> 
> @muttaqin1 
> 
> bot description
> `
> Directly incorporating user input into a URL redirect request without validating the input can facilitate phishing attacks. In these attacks, unsuspecting users can be redirected to a malicious site that looks very similar to the real site they intend to visit, but which is controlled by the attacker.
> `
> 

In the github controller you can see two destructured props **code, path**.
remove the _path_ prop. Create a environment variable **path**.Redirect user using that path var.

**Comment by muttaqin1** [comment]
> but the redirect url is a dynamic thing isn't ?
> @muttaqin1 

The frontend will provide the redirect_url and we will add it to the .env statically. Otherwise this will be vulnerable to phishing attacks.
@bellaabdelouahab

**Comment by muttaqin1** [comment]
I have done this previously.Then we have started using cookies so i have decided to redirect user directly. But this is a **GET** request so the response directly opens in the browser window.The user can see the response. How you will do it?
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
i see some sites opens a second browser window to do the authentication and then close it after that, will it help 
@muttaqin1

**Comment by bellaabdelouahab** [comment]
I think this will be an easy fix

**Comment by muttaqin1** [comment]
> I think this will be an easy fix

How you will fix it? I am very curious about it!
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
using a second window !!?

**Comment by bellaabdelouahab** [comment]
but after I thought about it, it is a front-end task , wht do you think ?
- in you github handler you need to fix it so it doesnt redirect and it only login the user 
- you need to add (else) so it doesnt create the user if the user already exists

@muttaqin1

**Comment by bellaabdelouahab** [comment]
@muttaqin1

**Comment by muttaqin1** [comment]
> but after I thought about it, it is a front-end task , wht do you think ?
> - in you github handler you need to fix it so it doesnt redirect and it only login the user 
> - you need to add (else) so it doesnt create the user if the user already exists
> 
> @muttaqin1  

Okay, i am working on it.

**Comment by muttaqin1** [comment]
@bellaabdelouahab
