### ISSUE TITLE
change from java script to typescript [front-end]

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#13]
Boosting frontend development with TypeScript's statically-typed superpowers, bid farewell to runtime surprises, embrace strictness, and level up your codebase

**Comment by Khalid1G** [comment]
The frontend I submitted , already uses TypeScript.

**Comment by bellaabdelouahab** [comment]
good then there is no need for this @bouslama-hamza
