### ISSUE TITLE
missing file base_controller in routes

### ISSUE THREAD

**Issue by GiovanniCaiazzo01** [ISIL-ESTE/Student-Workflow-Organizer#136]
Hi, 

in  `backend-app/routes/calendar_routes` there is an import for `base_controller` in the same folder, but actually, this file does not exist, I found another file called base_controller but is under the folder controllers.

does the import at row 2 actually refer to the base_controller in controllers?

```js
const express = require('express');
const base = require('./base_controller');
const calendarModel = require('../models/calendar/calendar_model');
const authController = require('../controllers/auth_controllers/auth_controller');
const router = express.Router();


router.post('/', base.createOne(calendarModel));
router.get('/:id', base.getOne(calendarModel));

router.patch('/:id', base.updateOne(calendarModel));
router.delete('/:id', base.deleteOne(calendarModel));

router.use(authController.restrictTo('ADMIN', 'SUPER_ADMIN'));

router.get('/', base.getAll(calendarModel));

module.exports = router;

```

**Comment by bellaabdelouahab** [comment]
i see what you mean 
the base controller is the targeted one 
the new import when converted to ts should be : import * as base from '@controllers/base_controller';

@GiovanniCaiazzo01

**Comment by GiovanniCaiazzo01** [comment]
Perfect, thanks for clarifying my doubts. @bellaabdelouahab
