### ISSUE TITLE
Enhance : Validate env variables 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#137]
as the project grows it will be little bit hard to setup all the env variables at once, 
and the new contributors might struggle to get the app to work
so for that i suggest to make and error handling for the env variables, 
- the errors should state the problem and help the developer with instruction on how to fix it

**Comment by muttaqin1** [comment]
We can validate the env var's with joi before starting the server.can i take it?

**Comment by bellaabdelouahab** [comment]
looks nice that is what i was waiting for 
@muttaqin1
