### ISSUE TITLE
TSOA - Route Versioning 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#154]
In our previous behavior, we used to do something like this:
```ts
routes
app.use(
    `/api`,
    routesVersioning()({
        '1.0.0': indexRouter,
    })
);
```

but now that we have switched to TSOA, we do not have the option to control what routes get triggered  based on api version in the header 

```ts
RegisterRoutes(app);
```

so we will need a new approach for API versioning

**Comment by muttaqin1** [comment]
This middleware will be initialized before all the routes.
```js
const version_middleware= (req, res, next) => {
  const acceptedVersion = req.get('accept-version')
  const basePath = '/api'
  const routePath = `${basePath}/${acceptedVersion}`
  req.url = req.url.replace(basePath, routePath) //Modify the request url to route to the versioned controller.
  next();
}
```
**NOTE: This is just my idea. Test this and let me know if this works or not.**

**Comment by muttaqin1** [comment]
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
@muttaqin1 I've already tested it; it changed the url, but the url that controls the request is not changeable.
you can only change which function to call
