### ISSUE TITLE
TSOA - fix multiple response message with the same status code 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#158]
what do you think about this :

file --> backend-app\node_modules\@tsoa\cli\dist\cli.js 

```ts
    buildOperation(controllerName, method, defaultProduces) {
        const swaggerResponses = {};
        method.responses.forEach((res) => {
            if (swaggerResponses[res.name]) {
                swaggerResponses[res.name].description += ` \n - ${res.description}`;
            } else {
                swaggerResponses[res.name] = {
                    description:  '- '+ res.description,
                };
            }
```
i have modified tsoa package to achive the aproach of multiple response with same status code : 

```ts
    @Response(400, 'Please provide email and password')
    @Response(400, 'Invalid email or password')
    @Response(400, 'You haven\'t set a password yet. Please login with GitHub and set a password from your profile page.')
    public async login(
        @Request() _req: Express.Request,
        @Res() res: TsoaResponse<200, { accessToken: string; user: any }>,
        @Body() body?: { email?: string; password?: string }
    ): Promise<void> {}
```
it is working but the problem is that any one who installs the project he will need to modify the package !
what do you think ? can you find a better aproach ? or should we just keep it as it was

@muttaqin1

**Comment by muttaqin1** [comment]
You can fork the **tsoa** repo. Make the necessary changes in your fork. Then in your terminal paste this command.

```txt
npm i user_name/repo_name
```
The modified version of the package will be installed. We can pull new changes from the original repo by syncing the fork then update the package using npm
```txt
npm update user_nme/repo_name
```

- You can submit a pr in **tsoa**.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Wait ! I don't have to create a package or build it or what ? And are you saying to perform npm install from GitHub even though it is not registered in npm ?
@muttaqin1

**Comment by muttaqin1** [comment]
> Wait ! I don't have to create a package or build it or what ? And are you saying to perform npm install from GitHub even though it is not registered in npm ?
> @muttaqin1 

Yeah, this should work. Can you try this at once? Because npm lib's are hosted on GitHub.

**Comment by muttaqin1** [comment]
You dont have to register it on npm. @bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
okay i will test it

**Comment by muttaqin1** [comment]
Any updates?
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
I found many approaches, but none of them worked. If you have any idea, then please suggest it; other than that, We will just leave it as an issue for an other time
@muttaqin1

**Comment by muttaqin1** [comment]
We can leave it for now. I will try to resolve this issue later. 
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
@muttaqin1 found anything ?

**Comment by muttaqin1** [comment]
> @muttaqin1 found anything ?

No bro. I thought [this](https://github.com/ISIL-ESTE/Student-Workflow-Organizer/issues/158#issuecomment-1815002629) will work. But as you have said that is not working now we can create a issue in tsoa github repo and wait or leave it as it is 😥😥😥

**Comment by bellaabdelouahab** [comment]
For now we leave the old approach @muttaqin1 
I'll colse this as not planned
