### ISSUE TITLE
Fix code scanning alert - Database query built from user-controlled sources

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#17]
```js
exports.updateOne = Model => async (req, res, next) => {
    try {
        const doc = await Model.findByIdAndUpdate(req.params.id, req.body, {
//...
```
This query depends on user input 
If a database query (such as a SQL or NoSQL query) is built from user-provided data without sufficient sanitization, a malicious user may be able to run malicious database queries.

**Comment by muttaqin1** [comment]
which validator should i use? JOI or express-validator?

**Comment by bellaabdelouahab** [comment]
You can leave it to someone else 😁

**Comment by Khalid1G** [comment]
@bellaabdelouahab I think it's not a big deal where we using ```
app.use(mongoSanitize()); ```
 This will entirely get rid of any inputs with prohibited characters in MongoDB like the ‘$’ sign.

```js
app.use(
  mongoSanitize({
    replaceWith: '_',
  }),
);
```
You can add the above snippet to replace any prohibited characters with a ‘-’ character otherwise.

**Comment by bellaabdelouahab** [comment]
unless there is more functionalities to add in this issue I suggest to merge this branch [khalid/back] to the main one cause they are related
@Khalid1G
