### ISSUE TITLE
add logic for banned users 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#23]
restrict access for all routes except for contact [until the contact logic implemented]

**Comment by bellaabdelouahab** [comment]
also the http response for banned users should be implemented

@muttaqin1

**Comment by muttaqin1** [comment]
> also the http response for banned users should be implemented
> 
> @muttaqin1 
> 

Yeah i will check if the user is banned in the login route.if banned the user will receive a 403

**Comment by bellaabdelouahab** [comment]
No for now we are still on api dev, do you think we should leave it for later

**Comment by muttaqin1** [comment]
no,  the reason for asking is the user will receive 2 jwt token access & refresh.the Access token will be expired in 10 minutes .So the frontend dev have to add the functionality to send a http request with the refresh token in every 7 or 6 minutes. every time the frontend dev will receive a new access token. so if the login feature is already implemented in the frontend. the frontend dev have to update the code.
@bellaabdelouahab

**Comment by muttaqin1** [comment]
can i use RS256 alg to sign and verify jwt tokens? 
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Sure 👍
