### ISSUE TITLE
Advantages of Postman Docs for Team Collaboration

### ISSUE THREAD

**Issue by Khalid1G** [ISIL-ESTE/Student-Workflow-Organizer#30]
I wanted to suggest a change in our documentation practices that I believe will greatly benefit our workflow and make our documentation more user-friendly. I propose transitioning from YML docs to Postman Docs.

Postman Docs offer a simplified and easy-to-read format, making it effortless to create and understand documentation. They provide clear and concise examples of request and response structures, which can greatly enhance the readability of our documentation.

One of the standout features of Postman Docs is the ability to execute API requests directly within the documentation. This feature allows us to test and verify our APIs without leaving the documentation environment. It's a fantastic way to streamline our development process and ensure accuracy.

Additionally, Postman Docs are widely used and well-supported in the developer community: https://docs.spacexdata.com/

**Comment by muttaqin1** [comment]
I am agree with you.
Its so hard to create documentation with swagger🤕.
btw, swagger also has the ability to execute API requests directly within the documentation too.

**Comment by Khalid1G** [comment]
swagger When spring boots are used, I find it cool. However, I believe that for this project, Postmen Docs will be sufficient. I frequently work with Postmen Docs since it is very simple to use.
