### ISSUE TITLE
rate limiter should be configured to ignore WebSocket and SSE

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#36]
Hi everyone,

I noticed on one of my latest projects that the rate limiter is affecting WebSocket and SSE connections. In order to improve the user experience and ensure smooth real-time communication, I suggest configuring the rate limiter to ignore WebSocket and SSE requests. This will allow uninterrupted data streaming and reduce unnecessary restrictions.

**Comment by Khalid1G** [comment]
@bellaabdelouahab are you sure that the rate limiter is affecting WebSocket I know the rate limit is applied only for `HTTP` requests in `prod`  instead of that WebSocket is use another protocol like `wws`. That means when you use the rate limit is just for express rotter.

**Comment by bellaabdelouahab** [comment]
ah you re right i tested it with only SSE which uses http 
@Khalid1G

**Comment by bellaabdelouahab** [comment]
@Khalid1G i will take this one 👌
