### ISSUE TITLE
Logger not defined on certain files

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#37]
when I was running test I faced issue with Logger not being defined, and also in the past I faced same issue with different files 
is storing Logger in global really the best approach because as I see it now it only reduces one line for each file 😂

@Khalid1G 
@muttaqin1

**Comment by muttaqin1** [comment]
The best approach will be using console.logs 😂

**Comment by bellaabdelouahab** [comment]
nice joke, but keep it one local code 😂

**Comment by Khalid1G** [comment]
is morgen not enough? I ask to improve my SPE 😂

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
no it is enough but there is some errors with it needs to be fixed in term of accessibility, I'm working on it
