### ISSUE TITLE
Feature : when no api version is provided use the most recent one 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#39]
I think it's good to have this feature so that when we publicize the API, it can be easily accessed by front-end developers and other third-party apps.

**Comment by bellaabdelouahab** [comment]
@yassineboujrada  
i found the best approach to achieve this behavior 
we can use ` express-routes-versioning` package whish allow us to do something like 
```js
app.use(`/api`,  routesVersioning(
    {
        '1.0.0': require('./routes/v1.0.0/index'),
    }
));
```

and the api request should contain this header :

'accept-version': "1.0.0"

**Comment by yassineboujrada** [comment]
👍
