### ISSUE TITLE
fix - refresh token , store generated token 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#46]
- implement basic refresh token
- store generated tokens on the database 

Develop a secure token refresh feature and establish token storage in the database for reliable access and management.

**Comment by muttaqin1** [comment]
This feature is required to implement logout functionality.
_store generated token in database._
Do you mean directly store jwt token in db?

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Yes
@muttaqin1
And btw i have some exams these days that why i wasn't available,
you can work with @yassineboujrada
I trust you guys 😁

**Comment by muttaqin1** [comment]
> Yes
> @muttaqin1
> And btw i have some exams these days that why i wasn't available,
> you can work with @yassineboujrada
> I trust you guys 😁

sounds good. i also have exams after this month😁. 
I will resolve this issue and who will be reviewing the pr you or @yassineboujrada ?

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
@muttaqin1 don't worry i will take some time to review, even tho your code doesn't really need that much of review 😁

**Comment by muttaqin1** [comment]
Glad to hear that😁
@bellaabdelouahab

**Comment by muttaqin1** [comment]
Which one is best?
- A
sign accessToken and refreshToken.

**No rsa algorithm will be  used to sign those tokens(Which i have done before).
**
**Token will be directly stored in the db**
and then  implement _logout_ feature.

- B
Sign a single jwt token like what we have now.
**Store that token in db**
and implement logout feature.

@bellaabdelouahab

**Comment by muttaqin1** [comment]
- Sign accessToken and refreshToken.
- store that token directly in db.
- add functionality to refresh access token with refresh token.
- add functionality to logout.

This is my plan do you want to add something?
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
looks great but you can do them one at a time, so i can keep up with testing 
@muttaqin1
