### ISSUE TITLE
fix - roles management 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#47]
on  my testing, i need these things to be fixed 
- [ ] add route /me for user crud that are protected 
- [ ] a user shouldn't be able to updated roles
- [ ] if user tries to updated password we replay with ( 400, This route is not for password updates. Please use /updateMyPassword )
- [ ] admin can update roles of users and admins but not supper admin. 

> note : we can add a restriction called updated admin, to prevent the fight between admins 😂

- [ ] supper admin can updated any role of any user except his. 
- [ ] return a valid message on jwt expired, as for now it returns 500
- [ ] separate the routes login and sign up from the rest as they are the only unprotected routes ( suggestion : put them in app.js)

**Comment by bellaabdelouahab** [comment]
@muttaqin1 @Khalid1G

**Comment by muttaqin1** [comment]
let's divide the tasks.I will take half of  them.now you decide should i take upper half or lower half?
and give me a deadline.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
No it's fine I'll do them all, I'm just worried that you may not be able to merge them if you started changing files name while I'm editing.


@muttaqin1 
Take your time 👌

**Comment by muttaqin1** [comment]
i havent started. Then you finish all the task and then tell me i will pull the changes then finish #23
