### ISSUE TITLE
Creating a calendar Model

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#77]
In this issue I want to discuss how should we create  the calendar model 
I have create some sort of diagram just to brain storm some ideas about the calendar and its functionalities .

__
![image](https://github.com/ISIL-ESTE/Student-Workflow-Organizer/assets/81409194/1b9d3aec-b27b-43d9-98b0-7a95fa9c5481)

this is just a basic example to be modified later,
please leave your opinions on this.

**Comment by bellaabdelouahab** [comment]
@Khalid1G

**Comment by bellaabdelouahab** [comment]
and here is a basic example of the class diagram of calendar :
![image](https://github.com/ISIL-ESTE/Student-Workflow-Organizer/assets/81409194/9c49c2dd-97e2-4273-b1d5-9270e29141b9)

**Comment by Khalid1G** [comment]
@bellaabdelouahab 
can you give the diagram as a [PlantUML](https://plantuml.com/) code

**Comment by bellaabdelouahab** [comment]
Sure @Khalid1G

**Comment by bellaabdelouahab** [comment]
here you go :
```
@startuml

class Calendar {
  - calendarId: int
  - calendarName: string
  - calendarType: CalendarType
  - isPublic: bool
  - isShared: bool
  - owner: User
  - participants: List<User>
  - events: List<Event>
  - reminders: List<Reminder>
  - permissions: List<Permission>
  - creationDate: DateTime
  - createdBy: User
  - lastModifiedDate: DateTime
  - lastModifiedBy: User
  - description: string
  - accessCode: string
  - privacySettings: PrivacySettings
  - isSyncEnabled: bool
  - attachment: byte[]
  - tags: List<string>
  - categories: List<Category>
  - allowedUsers: List<User>
  - deniedUsers: List<User>
}

class User {
}


class Event {
}

class Reminder {
}

class Permission {
}

class PrivacySettings {
}
Calendar -- User: owner
Calendar "0" -- "n" User: participants
Calendar "0" -- "n" Event: events
Calendar "0" -- "n" Reminder: reminders
Calendar "0" -- "n" Permission: permissions
Calendar -- PrivacySettings: privacySettings
Calendar "0" -- "n" User: allowedUsers
Calendar "0" -- "n" User: deniedUsers

@enduml
```



![image](https://github.com/ISIL-ESTE/Student-Workflow-Organizer/assets/81409194/17a4cefe-c324-4b0f-9d35-9c560f99d183)

**Comment by bellaabdelouahab** [comment]
@Khalid1G @muttaqin1 what do you think

**Comment by muttaqin1** [comment]
> @Khalid1G @muttaqin1 what do you think
looks fine.
