### ISSUE TITLE
Request for Project Design Ideas

### ISSUE THREAD

**Issue by yassineboujrada** [ISIL-ESTE/Student-Workflow-Organizer#80]
Hey everyone,
We're working on an exciting project and would love to hear your ideas and suggestions for its design. 

## Scope:
We're looking for design ideas related to the following aspects of the application:

- User Interface (UI) design for the app, including color schemes, and icons.

- Data management and storage ideas to handle user activity data and workout plans efficiently and securely.

## Guidelines:
Feel free to be creative and think outside the box. We're open to innovative ideas! or any examples of designs to start.
@bellaabdelouahab @Khalid1G @muttaqin1

**Comment by bellaabdelouahab** [comment]
@yassineboujrada 
just to not keep you waiting here is what I have done so far,  [Figma File]( https://www.figma.com/proto/ZNk6SbBCsN1ybz1Pbo3V7u/Untitled?type=design&node-id=4-37&t=ZtyEbBP3bVox6qYM-1&scaling=min-zoom&page-id=0%3A1&mode=design )
if anyone want to help just ask me to send edit link

**Comment by yassineboujrada** [comment]
okay thanks

**Comment by bellaabdelouahab** [comment]
@yassineboujrada here is what I have achieved so far 

![image](https://github.com/ISIL-ESTE/Student-Workflow-Organizer/assets/81409194/fdad4da3-d477-4f03-b95a-701c22d1a330)

this section represent a calendar page, I'm planning to add the calendar by tomorrow 

All though I'm not a designer, and the hole idea isn't yet clear

**Comment by bellaabdelouahab** [comment]
how is it going so far 
@yassineboujrada
