### ISSUE TITLE
Two eslintrc in dev branch 

### ISSUE THREAD

**Issue by muttaqin1** [ISIL-ESTE/Student-Workflow-Organizer#82]
One config is in .js format and one .json format. 
The .js config extends prettier. So we can directly copy all the rules from the .json config and remove that file.

What do you think? @bellaabdelouahab @Khalid1G

**Comment by bellaabdelouahab** [comment]
I also have a qstn, why can't we put it in base folder of the project this way we can apply it for both front and backend.
@muttaqin1

**Comment by muttaqin1** [comment]
> I also have a qstn, why can't we put it in base folder of the project this way we can apply it for both front and backend.
> @muttaqin1 

Yes we can. But i have seen many open source projects to use different config for frontend and backend. we have some airbnb eslint plugins for react.

If we use a single eslint config with the react plugin. In the frontend the code will be okay but in the Backend you will see a bunch of errors. So that's why people use seperate config for frontend and backend.

But if you still want a single config for both frontend and backend. You can move the config in the base path and add this code in your vscode settings.json file:

```json
"eslint.options": {
  "configFile": "path/to/your/.eslintrc"
}
```
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
no I didn't mean the same config for both i meant putting husky in base project instead of creating two husky folders 
@muttaqin1

**Comment by muttaqin1** [comment]
> no I didn't mean the same config for both i meant putting husky in base project instead of creating two husky folders 
> @muttaqin1 

Yeah ,just you have to tweak the prepare script.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
sounds good what do you think ?
@muttaqin1

**Comment by muttaqin1** [comment]
> sounds good what do you think ?
> @muttaqin1 

Perfect, Then you move the eslintrc.json rules to eslintrc.js and i am moving .husky to the base dir. 
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
sorry but I'm not sure how 🤨
@muttaqin1

**Comment by muttaqin1** [comment]
> sorry but I'm not sure how 🤨
> @muttaqin1 

You just have to copy all the rules in the eslintrc.json file. Then paste the rules in the eslintrc.js file. Thats why i have created the issue.

I will handle all the husky related tasks.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
okay sure 👌
